### ISSUE TITLE
Duplicate functions in Functions.php

### ISSUE THREAD

**Issue by AXeL-dev** [nouraellm/Lighty#2]
It seems like all the functions are duplicated in the end of the file starting from here

https://github.com/nouraellm/Lighty/blob/a1f3070cc09384d261729ff63ebfc203d0017b1e/conf/Functions.php#L85-L96

**Comment by AXeL-dev** [comment]
@nouraellm i cannot reply on the conversation

![Deepin Capture-écran_zone de sélection _20190507191651](https://user-images.githubusercontent.com/30635693/57326795-ccb51600-70fc-11e9-9fae-8d491761eb44.png)

So to answer you, all the functions are duplicated, the duplicates starts from line 85.

**Comment by nouraellm** [comment]
you can

**Comment by AXeL-dev** [comment]
yeah, i did, anyway see you after eating XD

**Comment by nouraellm** [comment]
Not duplicated, but checks if the function exists, if not it has to be created

**Comment by nouraellm** [comment]
xD OMG You're right xDDDDDD oh my bad dunno how it happened, however fix it or let me fix that later

**Comment by AXeL-dev** [comment]
you didn't get me XD see this the IP function is defined here

https://github.com/nouraellm/Lighty/blob/a1f3070cc09384d261729ff63ebfc203d0017b1e/conf/Functions.php#L1-L13

and here

https://github.com/nouraellm/Lighty/blob/a1f3070cc09384d261729ff63ebfc203d0017b1e/conf/Functions.php#L85-L96

& it's the same for all functions, they are also duplicated (maybe you did a copy & paste without paying attention).

**Comment by nouraellm** [comment]
yup I noticed xD as I said remove them or I will later.

**Comment by AXeL-dev** [comment]
To know: if you want to reference a commit in an issue just add the issue number in the commit message like so: `my commit message #2`

**Comment by nouraellm** [comment]
noted, thankies x3
